### ISSUE TITLE
feat:g729 transcending support at rtpengine 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/sbc-inbound#142]
its important to support g729 codec , since some of the system insist on using g729 , and this transcending needs to happen on rtpengine rather then freeswitch

**Comment by davehorton** [comment]
We will have a look at adding this feature, but keep in mind that G.729 is not recommended for conversational AI.  The quality will be poor due to 8k sampling vs 64k sampling of G711.  Poor audio quality is expected, this is a compression codec used typically when bandwidth is limited and there is a quality tradeoff

**Comment by davehorton** [comment]
@vdharashive can you supply an example INVITE showing the SDP that is being offered with a G.729 preference?

**Comment by vdharashive** [comment]
Thanks @davehorton
